#!/bin/bash

# Name:         vimer
# By:           Dupton
# Date:         2018-02-26
# Desc:         ~ edit now ~
# ------------------------------------------------------


KST_PATH=init_kst_path_once

####################

# check kst_path
[[ ! -d $KST_PATH ]] && echo "│ Warning:
├───── Can not find directory '${KST_PATH}'" && exit 0

# get short name from parameter $1
SN=$1

# declare -A filedict
# filedict=( ["mine"]="haha" ["fir"]="ceshi" )
# echo ${filedict[*]}

ShortNameList=("sh" "py" "php" "web" "dos" "mv" "ms" "t" "mine")
FileList=(
"$KST_PATH/Notes/Linux.nts"
"$KST_PATH/Notes/Python.nts"
"$KST_PATH/Notes/PHP.nts"
"$KST_PATH/Notes/Web.nts"
"$KST_PATH/Notes/Dos.nts"
"$KST_PATH/___PRIVACY___/Hobbies/Movie.txt"
"$KST_PATH/___PRIVACY___/Hobbies/Music.txt"
"$KST_PATH/../___私人生活___/Scrt/Privacy/Tips.txt"
"$KST_PATH/../___私人生活___/Scrt/Privacy/mine.hwaf"
)

####################


# check & show ShortName list
if [[ -z $SN || "$SN" = "ls" ]]; then
	echo -e "│ File list:
├───── \033[37;44m${ShortNameList[*]}\033[0m" && exit 0
fi

SIGN=0
for ((i=0; i<${#ShortNameList[@]}; i++)); do
	if [ "${ShortNameList[$i]}" = "$SN" ]; then
		cur_file=${FileList[$i]}
		# ls -plus $cur_file
		[ -f $cur_file ] && vim $cur_file && SIGN=1 && break
	fi
done

[[ $SIGN -eq 0 ]] && echo -e "│ Warning: 
├───── No such file '$SN', plz try file list: \033[37;44m${ShortNameList[*]}\033[0m"
